---
title: "Tidymodels and Classification on Palmer Penguin Data"
author: "Gaurav Sharma"
date: "27/08/2020"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, dpi = 180, fig.width = 8, fig.height = 5, warning = FALSE, message = FALSE)
library(tidyverse)
library(tidymodels)
```

### Reading the files
```{r}
ttfile <- tidytuesdayR::tt_load('2020-07-28')
penguins <- ttfile$penguins
```

### let's explore the data to see if we can find some good features to classify male and female penguins
```{r}
penguins %>% 
    drop_na() %>%
    pivot_longer(bill_length_mm:body_mass_g, names_to = 'spec', values_to = 'value') %>% 
    ggplot(aes(x= value, y = sex, fill = sex)) +
    geom_boxplot(color = "gray") +
    facet_wrap(~spec, scales = "free_y") +
    coord_flip() +
    labs(title = "Body Specs clearly show a difference in male and female penguins")
```

```{r}
penguins %>% 
    filter(!is.na(sex)) %>% 
    ggplot(aes(flipper_length_mm, bill_length_mm, color = sex, size = body_mass_g)) +
    geom_point(alpha = 0.5) +
    facet_wrap(~species) +
    labs(title = "Flipper and bill length can be used to differentiate between male and female penguins")
```

